# Generated by Selenium IDE
import pytest
import time
import json
import unittest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewAccount(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.maximize_window()

    def tearDown(self):
        self.driver.quit()
    #login
    def test_NA0(self):
        self.driver.get("https://demo.guru99.com/V4/")
        # self.driver.set_window_size(1534, 912)
        self.driver.maximize_window()
        self.driver.find_element(By.NAME, "uid").click()
        self.driver.find_element(By.NAME, "uid").send_keys("mngr615627")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("EmUqujY")
        self.driver.find_element(By.NAME, "btnLogin").click()
        # self.driver.find_element(By.CSS_SELECTOR, ".heading3 > td").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".heading3 > td").text == "Manger Id : mngr615627"

    #customer id field
    def test_NA1(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.find_element(By.LINK_TEXT, "New Account").click()

        customer_id_field = self.driver.find_element(By.NAME, "cusid")
        customer_id_field.click()
        # Shift focus to trigger validation
        customer_id_field.send_keys(Keys.TAB)

        error_message_element = self.driver.find_element(By.ID, "message14")

        actual_error_message = error_message_element.text
        expected_error_message = "Customer ID is required"
        self.assertEqual(actual_error_message, expected_error_message)

