# Generated by Selenium IDE
import pytest
import time
import json
import unittest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewCustomer(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.maximize_window()

    def tearDown(self):
        self.driver.quit()

    def test_NC0(self):
        self.driver.get("https://demo.guru99.com/V4/")
        # self.driver.set_window_size(1534, 912)
        self.driver.maximize_window()
        self.driver.find_element(By.NAME, "uid").click()
        self.driver.find_element(By.NAME, "uid").send_keys("mngr615627")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("EmUqujY")
        self.driver.find_element(By.NAME, "btnLogin").click()
        # self.driver.find_element(By.CSS_SELECTOR, ".heading3 > td").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".heading3 > td").text == "Manger Id : mngr615627"

    def test_NC1(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.find_element(By.LINK_TEXT, "New Customer").click()

        customer_name_field = self.driver.find_element(By.NAME, "name")
        customer_name_field.click()
        # Shift focus to trigger validation
        customer_name_field.send_keys(Keys.TAB)

        error_message_element = self.driver.find_element(By.ID, "message")

        actual_error_message = error_message_element.text
        expected_error_message = "Customer name must not be blank"
        self.assertEqual(actual_error_message, expected_error_message)

    def test_NC2(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1534, 912)
        self.driver.find_element(By.LINK_TEXT, "New Customer").click()
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("1234")
        self.driver.find_element(By.ID, "message").click()
        assert self.driver.find_element(By.ID, "message").text == "Numbers are not allowed"

# def test_NC3(self):
# check the excel file provided in the Project Submission Folder

# def test_NC4(self):
# check the excel file provided in the Project Submission Folder
