# Generated by Selenium IDE
import pytest
import time
import json
import unittest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class BalanceEnquiry(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.maximize_window()

    def tearDown(self):
        self.driver.quit()

    def test_login(self):
        self.driver.get("https://demo.guru99.com/V4/")
        # self.driver.set_window_size(1534, 912)
        self.driver.maximize_window()
        self.driver.find_element(By.NAME, "uid").click()
        self.driver.find_element(By.NAME, "uid").send_keys("mngr615627")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("EmUqujY")
        self.driver.find_element(By.NAME, "btnLogin").click()
        # self.driver.find_element(By.CSS_SELECTOR, ".heading3 > td").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".heading3 > td").text == "Manger Id : mngr615627"

    def test_EB3(self):
        self.test_login()

        self.driver.execute_script("window.scrollTo(0, 300);")

        balance_link = self.driver.find_element(By.LINK_TEXT, "Balance Enquiry")

        time.sleep(1)

        # Hide footer and ads
        self.driver.execute_script("""
               let footer = document.querySelector('p.barone');
               if (footer) {
                   footer.style.display = 'none';
               }

               let ad = document.querySelector('img[alt="Try Xero for free"]');
               if (ad && ad.parentElement) {
                   ad.parentElement.style.display = 'none';
               }
           """)

        balance_link.click()

        # Stop the interval after click
        # self.driver.execute_script("clearInterval(window.adHiderInterval);")
        time.sleep(2)

        self.driver.find_element(By.NAME, "accountno").send_keys("123!@#")
        self.driver.find_element(By.XPATH, "/html/body/table/tbody/tr/td/table/tbody/tr[1]/td/p").click()
        time.sleep(2)
        error_message = self.driver.find_element(By.XPATH, "//*[@id='message2']").text
        assert error_message == "Special characters are not allowed"
